name: Run Hello World on EC2 via SSM

on:
  workflow_dispatch:

jobs:
  run_ssm_command:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run Hello World and Get Output
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters commands=ifconfig \
            --comment "Deploying comment" \
            --query "Command.CommandId" \
            --output text)
          echo "Command ID: $COMMAND_ID"
          echo "::set-output name=command_id::$COMMAND_ID"
      - name: Output execution via SSM
        id : output_execution
        run: |
          sleep 15s
          COMMAND_ID=${{ steps.execute_command.outputs.command_id }}
          aws ssm list-command-invocations \
            --details \
            --instance-id ${{ secrets.EC2_INSTANCE_ID }} \
            --query "CommandInvocations[].CommandPlugins[].{Status:Status,Output:Output}" \
            --command-id "$COMMAND_ID" \
            --output text
          
