name: Run Hello World on EC2 via SSM

on:
  workflow_dispatch:

jobs:
  run_ssm_command:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run Hello World and Get Output
        run: |
          INSTANCE_ID="${{ secrets.EC2_INSTANCE_ID }}"
          OUTPUT=$(aws ssm send-command \
            --instance-ids "$INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --parameters "commands=[\"echo 'Hello, World!'\"]" \
            --query "Command.CommandId" \
            --output text | xargs aws ssm wait command-executed --command-id --instance-id "$INSTANCE_ID" | xargs aws ssm get-command-invocation --command-id --instance-id "$INSTANCE_ID" --query "StandardOutputContent" --output text)
          echo "SSM_OUTPUT=$OUTPUT"
          echo $OUTPUT
